### PR TITLE
upgrade Vue2 to Vue3 in compatibility mode

### PR DESCRIPTION
**Pull request by rmotitsuki**
Related to issue #35 

### Summary
This PR replace the Vue2 framework for Vue3 in compatibility mode.
There is a new webpack option to enable the debug message in browser, to visualize the debug, warning and error messages.

This PR impacts in all NApps that use Kytos UI components. A manual with the main erros can be found in the comments [here](https://github.com/kytos-ng/ui/issues/35):

The font library had to be replaced for compatibility.

### Local Tests
To build Kytos UI:
$ npm run preprod 
copy build.js to your kytos/web-ui
$ cp dist/build.js ../ng/kytos/kytos/web-ui/dist/build.js

You can start Kytos and test the UI.

### CODE REVIEW

**Review by Alopalao — APPROVED** [review]
LGTM, checked and tested components.

**Review by viniarck — COMMENTED** [review]
@rmotitsuki, excellent contribution, fantastic to see the migration to Vue3 happening. 

1 - Can you also update the changelog accordingly?
2 - Also, can you elaborate on for how long we'll need to keep `@vue/compat`? Once we have Vue3 working in compatibility mode should we plan to try to also get rid of this compatibility layer or will it be too much effort? Will it be supported by upstream team for how long (can we rely on it for 1-2 years)? What's your thoughts and recommendation about it?

**Review by italovalcy — APPROVED** [review]
Looks good to me. Left a minor change suggestion on the bind-class for Menubar.vue

**Review by viniarck — APPROVED** [review]
LGTM. Leaving it pre-approved. Nicely done @rmotitsuki. 

I just noticed this `v-bind` warning though when running `npm run preprod`:

```
WARNING in ./src/components/kytos/inputs/InputAutocomplete.vue?vue&type=template&id=70ccfce1 (./node_modules/vue-loader/dist/templateLoader.js??ruleSet[1].rules[2]!./node_modules/vue-loa
der/dist/index.js??ruleSet[0]!./src/components/kytos/inputs/InputAutocomplete.vue?vue&type=template&id=70ccfce1)
Module Warning (from ./node_modules/vue-loader/dist/templateLoader.js):
(Emitted value instead of an instance of Error) (deprecation COMPILER_V_BIND_OBJECT_ORDER) v-bind="obj" usage is now order sensitive and behaves like JavaScript object spread: it will no
w overwrite an existing non-mergeable attribute that appears before v-bind in the case of conflict. To retain 2.x behavior, move v-bind to make it the first attribute. You can also suppr
ess this warning if the usage is intended.
  Details: https://v3-migration.vuejs.org/breaking-changes/v-bind.html
53 |              <ul v-bind="resultListProps" v-on="resultListListeners">
54 |                <template v-for="(result, index) in results" :key="resultProps[index].id">
55 |                  <li v-bind="resultProps[index]">
   |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
56 |                    {{ result }}
57 |                  </li>
 @ ./src/components/kytos/inputs/InputAutocomplete.vue?vue&type=template&id=70ccfce1 1:0-213 1:0-213
 @ ./src/components/kytos/inputs/InputAutocomplete.vue 1:0-78 8:68-74
 @ ./src/main.js 45:0-85 92:32-54
```

Should this be mapped in a new issue to be handled later?

**Comment by rmotitsuki** [comment]
COMPILER_V_BIND_OBJECT_ORDER is a possible breaking change in Vue3.
I was unable to remove this warning in this component, despite it being a warning that doesn't make sense in this case.
I think we can remove it globally, but it's risky.
We can take care of that later in another issue.

**Comment by viniarck** [comment]
img

**Pull request merged**
